Develop
openimis/openimis-be-api_fhir_py pull request #29
Opened 2019-12-09 09:35 UTC by kingtvarshin

Insuree filter applied and extension added and wiki urls added

2020-02-04 07:40 UTC, areklalo requested changes

2020-02-04 07:40 UTC, areklalo commented on api_fhir/converters/patientConverter.py
> +        # flag = views.InsureeViewSet.check_for_extension(views.InsureeViewSet,request)
Please remember to remove these comments if they are unnecessary

2020-02-04 07:40 UTC, areklalo commented on api_fhir/converters/patientConverter.py
> +        # if flag:
Same as above

2020-02-04 09:17 UTC, harsh-a1 commented on api_fhir/converters/patientConverter.py
> +        # flag = views.InsureeViewSet.check_for_extension(views.InsureeViewSet,request)
Done

2020-02-05 08:27 UTC, areklalo approved these changes

2020-02-05 08:28 UTC, areklalo commented
If you decide that the PR is ready to merge then kindly change the status from draft to "Ready for review".

2020-02-07 06:35 UTC, merged